### PR TITLE
Adds Gooey GUI for python API

### PR DESCRIPTION
**Pull request by sopu**
asdaerqrqewqe

### CODE REVIEW

**Comment by sudheesh001** [comment]
Looks great but this is windows only, so I suggest create a file `requirements_windows.txt` and add Gooey to it ! Once that's done this is good to merge, the existing CLI isn't broken with the changes on *nix systems.

**Comment by sudheesh001** [comment]
Also is it possible to release a binary for this and upload it as downloadable executable file ?

**Comment by sopu** [comment]
@sudheesh001 It requires wxPython which is available for all OSs. Once that is downloaded it should work for Mac and *nix as well!

**Comment by sopu** [comment]
@sudheesh001 Added!

**Comment by sopu** [comment]
@sudheesh001 Created an issue to release binary #43. 
Merging it for now!

**Pull request merged**
